const ProjectsList = [
  {url: 'https://the-unreasonable-challenge.firebaseapp.com/',
    src: require('../images/the-unreasonable-challenge.png'),
    title: 'The Unreasonable Challenge',
    name: 'the-unreasonable-challenge',
    description:'An application used to write about and complete challenges between users, built with React, JavaScript, Create-React-App, and CSS and uses Firebase for authentication. Users can log in, add images and challenges, count the times each challenge is completed, and comment on others challenges. Feel free to log in and add a challenge!',
    github:'https://github.com/hilarylewis92/the-unreasonable-challenge',
    id: 0,
  },

  {url: 'https://hilarylewis92.github.io/weather-forecast/#/?_k=myzv4x',
    src: require('../images/weather-dux.png'),
    title: 'Weather Dux',
    name: 'weather-dux',
    description: 'This weather application was built using React, React-Router, and Redux and tested with Jest and Enzyme. The application retrieves and displays forecast data from Weather Underground API, uses Geolocation to determine the weather in your current location, and saves favorite cities to display their forecasts. For each city, the user can display current forecast, ten day forecast, hourly forecast for each day, and delete any pinned cities.',
    github: 'https://github.com/hilarylewis92/weather-forecast',
    id: 1,
  },

  {url: 'https://nimblenetwork-d13c3.firebaseapp.com/',
    src: require('../images/nimble-network.png'),
    title: 'Nimble Network',
    name: 'nimble-network',
    description: 'Upon signing in through google using Firebase, the user can record name, company, email, social media, photo, and phone number of new contacts. There is a toggle on/off “followup” indicator on each contact, which will save those contacts in a “followup” list for quick reference. The application permits multiple options for email, phone, and social media, and allows the user to specify “primary” where applicable.',
    github: 'https://github.com/hilarylewis92/nimble-network',
    id: 2,
  },

  {url: 'https://github.com/hilarylewis92/number-guesser-react',
    src: require('../images/number-guesser-react.jpg'),
    title: 'Number Guesser',
    name: 'number-guesser',
    description: 'A game written in React where the user sets a minimum and maximum, a random number is automatically generated, and the user tries to guess the random number given clues upon each guess. Once the game is won, the application automatically increases and decreases the minimum and maximum by 10.',
    github: 'https://github.com/hilarylewis92/number-guesser-react',
    id: 3,
  },

  {url: 'https://shoot-the-breeze-1be68.firebaseapp.com/',
    src: require('../images/shoot-the-breeze.png'),
    title: 'Shoot the Breeze',
    name: 'shoot-the-breeze',
    description: 'A real time messaging application made with React and Firebase and tested using Enzyme. Upon login with google, the user can submit messages to other users in the chatroom. The input field for each message has a maximum character count of 140 which is displayed next to the input field. The submit and clear buttons are disabled appropriately to maximize user experience. A list of users contributing to the chatroom is listed based on the current messages being displayed. User can filter/search for messages. Chat messages display time stamp, user, and message.',
    github: 'https://github.com/hilarylewis92/shoot-the-breeze-1',
    id: 4,
  },

  {url: 'https://hilarylewis92.github.io/2DoBox-Pivot/',
    src: require('../images/game-time.png'),
    title: '2Do Box',
    name: '2do-box',
    description:'This is a simple to-do list application. The user can enter in tasks, updown or downvote them based on five levels of importance, delete tasks, and more. We used Selenium Webdriver to extensively test this application.',
    github: 'https://github.com/hilarylewis92/2DoBox-Pivot',
    id: 5,
  },
]

module.exports = ProjectsList
